[package]
name = "pacman"
version = "0.1.0"
authors = ["tl-thomas-pearson <thomas.pearson@truelayer.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.1.2"